<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Bundle\\SwiftmailerBundle\\' => array($vendorDir . '/symfony/swiftmailer-bundle'),
    'Symfony\\Bundle\\MonologBundle\\' => array($vendorDir . '/symfony/monolog-bundle'),
    'Symfony\\Bundle\\AsseticBundle\\' => array($vendorDir . '/symfony/assetic-bundle'),
    'Stof\\DoctrineExtensionsBundle\\' => array($vendorDir . '/stof/doctrine-extensions-bundle'),
    'Sonata\\DoctrineORMAdminBundle\\' => array($vendorDir . '/sonata-project/doctrine-orm-admin-bundle'),
    'Sonata\\CoreBundle\\' => array($vendorDir . '/sonata-project/core-bundle'),
    'Sonata\\Cache\\Tests\\' => array($vendorDir . '/sonata-project/cache/test'),
    'Sonata\\Cache\\' => array($vendorDir . '/sonata-project/cache/lib'),
    'Sonata\\BlockBundle\\' => array($vendorDir . '/sonata-project/block-bundle'),
    'Sonata\\AdminBundle\\' => array($vendorDir . '/sonata-project/admin-bundle'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'PHPMentors\\DomainKata\\' => array($vendorDir . '/phpmentors/domain-kata/src'),
    'Nelmio\\Alice\\' => array($vendorDir . '/nelmio/alice/src/Nelmio/Alice'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'Knp\\Snappy\\' => array($vendorDir . '/knplabs/knp-snappy/src/Knp/Snappy'),
    'Knp\\Bundle\\SnappyBundle\\' => array($vendorDir . '/knplabs/knp-snappy-bundle'),
    'Intervention\\Image\\' => array($vendorDir . '/intervention/image/src/Intervention/Image'),
    'Hautelook\\AliceBundle\\' => array($vendorDir . '/hautelook/alice-bundle'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'Fresh\\DoctrineEnumBundle\\' => array($vendorDir . '/fresh/doctrine-enum-bundle'),
    'Faker\\' => array($vendorDir . '/fzaninotto/faker/src/Faker'),
    'FOS\\UserBundle\\' => array($vendorDir . '/friendsofsymfony/user-bundle'),
    'Doctrine\\Bundle\\DoctrineBundle\\' => array($vendorDir . '/doctrine/doctrine-bundle'),
    'DoctrineExtensions\\' => array($vendorDir . '/beberlei/DoctrineExtensions/src'),
    'Cocur\\Slugify\\' => array($vendorDir . '/cocur/slugify/src'),
);
